shell.run("mkdir config")
shell.run("wget https://raw.githubusercontent.com/V0xelTech/KristKorner/master/src/config/main.xml?token=GHSAT0AAAAAAB4WFNPBI4SA5G3IVKX2D666Y5QYFVQ config/main.xml")
shell.run("wget https://raw.githubusercontent.com/V0xelTech/KristKorner/master/src/config/layout.xml?token=GHSAT0AAAAAAB4WFNPBG7ELZTMHYCUIQSLEY5QYGFA config/layout.xml")
shell.run("wget https://raw.githubusercontent.com/V0xelTech/KristKorner/master/src/dom.lua?token=GHSAT0AAAAAAB4WFNPA6HJF5EEUDEJ2ODVGY5QYGUA dom.lua")
shell.run("wget https://raw.githubusercontent.com/V0xelTech/KristKorner/master/src/krisapi.lua?token=GHSAT0AAAAAAB4WFNPB37LHN3OXHPQYPCWCY5QYG6A kristapi.lua")
shell.run("wget https://raw.githubusercontent.com/V0xelTech/KristKorner/master/src/main.lua?token=GHSAT0AAAAAAB4WFNPBUQNK4C2YUF2A23UKY5QYHRA main.lua")
shell.run("wget https://raw.githubusercontent.com/V0xelTech/KristKorner/master/src/r.lua?token=GHSAT0AAAAAAB4WFNPBLSVH7HE2LHBLB4EEY5QYH5Q r.lua")
shell.run("wget https://raw.githubusercontent.com/V0xelTech/KristKorner/master/src/w.lua?token=GHSAT0AAAAAAB4WFNPB3DPISAR3CUFMA2R2Y5QYILA w.lua")
shell.run("wget https://raw.githubusercontent.com/V0xelTech/KristKorner/master/src/xml.lua?token=GHSAT0AAAAAAB4WFNPAYY7PUSD4D4IJ5YHEY5QYIVA xml.lua")